"""Bake approved sculpted stone badges with real cavities, live-value lookup and masks.

The runtime selects a value texture; glyph masks carry only bonus illumination.
Unknown future values fall back to an empty engraved stone and readable text.
"""
import argparse,json,sys,math
from pathlib import Path
import bpy
p=argparse.ArgumentParser();p.add_argument('--root',type=Path,required=True);p.add_argument('--sample',action='store_true');p.add_argument('--resume',action='store_true');p.add_argument('--refresh-kind',default='')
a=p.parse_args(sys.argv[sys.argv.index('--')+1:]);root=a.root.resolve();sys.path.insert(0,str(root/'tools/art'))
bpy.ops.wm.open_mainfile(filepath=str(root/'art/production/samples/R2B02-Badges/R2B02_SemanticBadges.blend'))
from r2b02_stones import build_badge,poly
from r2b_runtime_common import materials,studio,render,floor_mask,emission
M=materials();font=bpy.data.fonts.load('C:/Windows/Fonts/georgiab.ttf')
out=root/'unity/Assets/Resources/UI3D/R2B';out.mkdir(parents=True,exist_ok=True)
sc,col=studio('R2B runtime stone variants',256,2.15,24)
kinds=('boot','shield','sword','skill','hourglass','range','distance')
values=[None,0,3,4,9,12,'∞'] if a.sample else [None,*range(-9,25),'∞']
manifest=[]
def token(v):return 'none' if v is None else 'inf' if v=='∞' else ('n'+str(-v) if v<0 else 'p'+str(v))
for kind in kinds:
    for value in ([None] if kind=='skill' else values):
        key=kind+'-'+token(value);target=out/(key+'.png');mask=out/(key+'-fill.png')
        manifest.append({'kind':kind,'value':str(value),'texture':key})
        if a.resume and kind!=a.refresh_kind and target.exists() and (value is None or mask.exists()):continue
        badge=build_badge(kind,value,col,M,font,tag='RUNTIME '+key)
        render(sc,target)
        if value is not None:
            floor=next(o for o in badge.children_recursive if o.get('recess_below_face'));floor_mask(sc,floor,mask,256)
        # A neutral metal overlay prevents card colour tinting semantic emblems.
        overlay=out/(kind+'-emblem.png')
        if not overlay.exists() or not a.resume:
            for ob in badge.children_recursive:ob.hide_render=not bool(ob.get('semantic_emblem'))
            render(sc,overlay)
        for ob in list(badge.children_recursive):bpy.data.objects.remove(ob,do_unlink=True)
        bpy.data.objects.remove(badge,do_unlink=True)
        print('R2B_BAKED '+key,flush=True)

# Frame keeps the approved segmented stone and mineral rim; card names/icons are
# separate keyed assets, so one player's text can never be baked into another's.
base=bpy.data.scenes['00_CORRECTED_BOOMERANG'];bpy.context.window.scene=base
for ob in base.objects:
    keep=ob.name.startswith(('Button /','Outer dressed stone','Red mineral band','Dark inner stone'))
    if ob.type not in ('CAMERA','LIGHT'):ob.hide_render=not keep
base.camera.location=(0,0,22);base.camera.rotation_euler=(0,0,0);base.camera.data.ortho_scale=6.5
base.render.resolution_x=base.render.resolution_y=768;base.cycles.samples=32;base.render.film_transparent=True;base.use_nodes=False
base.render.image_settings.color_mode='RGBA'
for color in ('gold','silver','red','green','blue','purple'):
    if a.resume and (out/('front-'+color+'.png')).exists():continue
    for ob in base.objects:
        if ob.name.startswith('Red mineral band'):ob.data.materials[0]=M[color]
    render(base,out/('front-'+color+'.png'))

bpy.context.window.scene=sc;gem=emission('R2B tier / golden inner fire',(1,.49,.065),2.5)
poly('Tier / dressed diamond socket',[(0,.9),(.54,0),(0,-.9),(-.54,0)],0,.20,col,M['edge'],.045)
poly('Tier / gold bevel',[(0,.78),(.43,0),(0,-.78),(-.43,0)],.18,.28,col,M['bronze'],.025)
poly('Tier / bright incised gold heart',[(0,.63),(.31,0),(0,-.63),(-.31,0)],.25,.29,col,gem,.01)
render(sc,out/'tier-gem.png')
bpy.context.preferences.filepaths.save_version=0
# Source contains the editable tier and original approved badge library; variants
# are reproducibly generated by the script, not hand-edited raster numerals.
source=root/'art/production/assets/R2BRuntime.blend';bpy.ops.wm.save_as_mainfile(filepath=str(source),compress=True)
(out/'manifest.json').write_text(json.dumps({'sample_only':a.sample,'values':manifest,'source':source.relative_to(root).as_posix(),'range':[-9,24],'numeric_method':'Real Blender boolean cavity plus its mesh-derived illumination mask'},ensure_ascii=False,indent=2),encoding='utf8')
print('R2B_RUNTIME_BAKE_DONE',flush=True)
