using System;
using System.Linq;
using Goa2.Application;
using Goa2.Domain;
using Goa2.Infrastructure;
using Goa2.Rules;
using NUnit.Framework;
using static Goa2.Tests.SessionTests;
using static Goa2.Tests.TurnFlowTests;
namespace Goa2.Tests
{
 public sealed class IronWallTests
 {
  internal const string Card="brogan-06-铜墙铁壁";
  internal static GameSession Setup(ContentCatalog cat,bool alliedSwap=false)
  {
   var g=LocalGameFactory.Create(cat,"iron-wall",new[]{"A","B","C","D"},42,true);Apply(g,0,CommandKind.DebugPrepare,alliedSwap?"brogan,wasp,arien,sabina":"brogan,wasp,sabina,arien");Apply(g,0,CommandKind.DebugEquipCard,"wasp-14-动力助推",target:1);Apply(g,0,CommandKind.DebugEquipCard,"arien-08-奥术换位",target:alliedSwap?2:3);
   Apply(g,0,CommandKind.DebugTeleport,"hero:0",cell:new Hex(-2,0));Apply(g,0,CommandKind.DebugTeleport,"hero:1",cell:new Hex(-1,0));Apply(g,0,CommandKind.DebugTeleport,"hero:2",cell:new Hex(-2,-1));Apply(g,0,CommandKind.DebugTeleport,"hero:3",cell:new Hex(6,-9));
   string[] cards={Card,"wasp-06-静电封锁",alliedSwap?"arien-08-奥术换位":"sabina-07-指挥",alliedSwap?"sabina-07-指挥":"arien-08-奥术换位"};for(int i=0;i<4;i++)Apply(g,i,CommandKind.SelectCard,cards[i]);Apply(g,1,CommandKind.Pass);Assert.That(g.View(0).ActiveSeat,Is.EqualTo(0));return g;
  }
  internal static CommandKind Choice=>(CommandKind)Enum.Parse(typeof(CommandKind),"ChoosePrimaryOption");
  internal static void Protect(GameSession g){Apply(g,0,CommandKind.BeginPrimary);Apply(g,0,Choice,"protect");}
  private static GameState State(GameSession g)=>new JsonStateCodec().Read(g.ExportSave());
  [Test] public void ContractAndEngineGate(){var c=BattlefieldTests.Catalog().Card(Card);Assert.That(c.Initiative,Is.EqualTo(5));Assert.That(c.SubtypeValue,Is.EqualTo(2));Assert.That(c.PrimaryCategory,Is.EqualTo("基础技能"));Assert.That(CombatRules.HasPrimaryProgram(c),Is.True);Assert.That(CombatRules.HasPrimaryProgram(c,49),Is.False);c.Text+="可选";Assert.That(CombatRules.HasPrimaryProgram(c),Is.False);}
  [Test] public void ProtectionChoicePersistsAndHasRoundLifetime(){var cat=BattlefieldTests.Catalog();var g=Setup(cat);Apply(g,0,CommandKind.BeginPrimary);g=ChargeTests.Restore(cat,g);Assert.That(g.View(0).Pending!.Kind,Is.EqualTo("primary_option"));Apply(g,0,Choice,"protect");var e=g.View(0).Effects.Single(x=>x.SourceCardId==Card);Assert.That(e.Duration,Is.EqualTo(EffectDuration.ThisRound));Assert.That(e.Window.EndTurn,Is.EqualTo(4));g=ChargeTests.Restore(cat,g);Assert.That(g.View(0).OwnCards.Single(c=>c.CardId==Card).Zone,Is.EqualTo(CardZone.PlayedResolved));}
  [Test] public void EmptyDiscardSelfRecoveryEndsActionOnceAndKeepsPlayHistory(){var cat=BattlefieldTests.Catalog();var g=Setup(cat);Apply(g,0,CommandKind.BeginPrimary);g=ChargeTests.Restore(cat,g);Apply(g,0,Choice,"recover");g=ChargeTests.Restore(cat,g);var card=g.View(0).OwnCards.Single(c=>c.CardId==Card);Assert.That(card.Zone,Is.EqualTo(CardZone.InHand));Assert.That(card.PlayedRound,Is.EqualTo(1));Assert.That(card.PlayedTurn,Is.EqualTo(1));Assert.That(g.View(0).Effects.Any(e=>e.SourceCardId==Card),Is.False);Assert.That(g.View(0).Events.Count(e=>e.Kind=="CardResolved" && e.CardId==Card),Is.EqualTo(1));Assert.That(g.View(0).ActiveSeat,Is.Not.EqualTo(0));Assert.That(g.View(1).Players[0].Plays.Any(p=>p.CardId==Card),Is.True);}
  [Test] public void OwnDiscardBlocksRecoveryButNotProtection(){var cat=BattlefieldTests.Catalog();var g=Setup(cat);Apply(g,0,CommandKind.DebugDiscard,"brogan-00-猛攻",target:0);Apply(g,0,CommandKind.BeginPrimary);var save=g.ExportSave();Assert.That(g.Execute(0,Cmd(g,0,Choice,"recover")).Accepted,Is.False);Assert.That(g.ExportSave(),Is.EqualTo(save));Apply(g,0,Choice,"protect");Assert.That(g.View(0).Effects.Any(e=>e.SourceCardId==Card),Is.True);}
  [Test] public void OtherPlayersDiscardDoesNotBlockSelfRecovery(){var cat=BattlefieldTests.Catalog();var g=Setup(cat);Apply(g,0,CommandKind.DebugDiscard,"wasp-00-闪耀之刃",target:1);Apply(g,0,CommandKind.BeginPrimary);Apply(g,0,Choice,"recover");Assert.That(g.View(0).OwnCards.Single(c=>c.CardId==Card).Zone,Is.EqualTo(CardZone.InHand));}
  [Test] public void NonOwnerAndUnknownOptionAreAtomicDuplicateDoesNotRepeat(){var cat=BattlefieldTests.Catalog();var g=Setup(cat);Apply(g,0,CommandKind.BeginPrimary);var save=g.ExportSave();Assert.That(g.Execute(1,Cmd(g,1,Choice,"protect")).Accepted,Is.False);Assert.That(g.Execute(0,Cmd(g,0,Choice,"skip")).Accepted,Is.False);Assert.That(g.ExportSave(),Is.EqualTo(save));var cmd=Cmd(g,0,Choice,"protect");Assert.That(g.Execute(0,cmd).Accepted,Is.True);save=g.ExportSave();Assert.That(g.Execute(0,cmd).Duplicate,Is.True);Assert.That(g.ExportSave(),Is.EqualTo(save));}
  [Test] public void EnemySwapCannotSelectProtectedMinion(){var cat=BattlefieldTests.Catalog();var g=Setup(cat);Apply(g,0,CommandKind.DebugTeleport,"hero:3",cell:new Hex(-2,1));Protect(g);if(g.View(0).ActiveSeat==2)Apply(g,2,CommandKind.Pass);Apply(g,3,CommandKind.BeginPrimary);Assert.That(g.View(3).EffectTargets,Does.Not.Contain("minion:-3,1"));Assert.That(g.View(3).EffectTargets,Does.Contain("hero:1"));}
  [Test] public void FriendlySwapStillMovesProtectedMinion(){var cat=BattlefieldTests.Catalog();var g=Setup(cat,true);Protect(g);Apply(g,2,CommandKind.BeginPrimary);Assert.That(g.View(2).EffectTargets,Does.Contain("minion:-3,1"));Apply(g,2,CommandKind.ChooseEffectTarget,"minion:-3,1");ChargeTests.Restore(cat,g);Assert.That(g.View(0).Events.Any(e=>e.Kind=="UnitsSwapped"),Is.True);}
  internal static void FinishTurn(GameSession g)
  {int steps=0;while(g.View(0).Phase==Phase.Action || g.View(0).Phase==Phase.InitiativeChoice){Assert.That(++steps,Is.LessThan(12));var v=g.View(0);if(v.Phase==Phase.InitiativeChoice)Apply(g,v.Pending!.ChooserSeat,CommandKind.ChooseInitiative,target:v.Pending.CandidateSeats.First());else Apply(g,v.ActiveSeat!.Value,CommandKind.Pass);}}
  private static void SelectNext(GameSession g,string wasp="wasp-14-动力助推",bool allySwap=false)
  {string[] cards={"brogan-00-猛攻",wasp,allySwap?"arien-13-挑战者":"sabina-00-近身射击",allySwap?"sabina-00-近身射击":"arien-13-挑战者"};for(int i=0;i<4;i++)Apply(g,i,CommandKind.SelectCard,cards[i]);}
  [TestCase(false)] [TestCase(true)] public void GroupPushUsesCurrentProtectionRange(bool outside)
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Protect(g);FinishTurn(g);Apply(g,0,CommandKind.DebugTeleport,"minion:1,0",cell:new Hex(-1,-1));if(outside)Apply(g,0,CommandKind.DebugTeleport,"hero:0",cell:new Hex(-6,1));SelectNext(g);while(g.View(0).ActiveSeat!=1)Apply(g,g.View(0).ActiveSeat!.Value,CommandKind.Pass);Apply(g,1,CommandKind.BeginPrimary);if(outside){Assert.That(g.View(1).EffectTargets,Does.Contain("minion:1,0"));Apply(g,1,CommandKind.ChooseEffectTarget,"minion:1,0");}else Assert.That(g.View(0).Events.Any(e=>e.Kind=="UnitPushed"),Is.False);ChargeTests.Restore(cat,g);}
  [Test] public void SelfAlliesEnemiesRangeAndControllerMatrixUsesRealProtectionEffect()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Protect(g);var s=State(g);var owner=s.Units.Single(u=>u.Seat==0);var friend=s.Units.Single(u=>u.Seat==2);Assert.That(EffectRules.CanDisplace(cat,s,1,owner),Is.False);Assert.That(EffectRules.CanDisplace(cat,s,1,friend),Is.False);Assert.That(EffectRules.CanDisplace(cat,s,0,friend),Is.True);Assert.That(EffectRules.CanDisplace(cat,s,1,s.Units.Single(u=>u.Seat==1)),Is.True);friend.Position=new Hex(-2,-3);Assert.That(EffectRules.CanDisplace(cat,s,1,friend),Is.True);s.Players[0].RangedBonus=5;Assert.That(EffectRules.CanDisplace(cat,s,1,friend),Is.True);s.Players[0].RangeBonus=1;Assert.That(EffectRules.CanDisplace(cat,s,1,friend),Is.False);owner.Position=new Hex(6,-8);Assert.That(EffectRules.CanDisplace(cat,s,1,friend),Is.True);}
  [Test] public void AttackStillResolvesButNearShotPushIsPrevented()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat,true);Protect(g);FinishTurn(g);Apply(g,0,CommandKind.DebugTeleport,"hero:3",cell:new Hex(-2,1));SelectNext(g,allySwap:true);Assert.That(g.View(0).ActiveSeat,Is.EqualTo(3));Apply(g,3,CommandKind.BeginPrimary);Assert.That(g.View(3).AttackTargets,Does.Contain("hero:0"));Apply(g,3,CommandKind.ChooseAttackTarget,"hero:0");Apply(g,0,CommandKind.Defend,"brogan-13-冲拳");ChargeTests.Restore(cat,g);Assert.That(State(g).Units.Single(u=>u.Seat==0).Position,Is.EqualTo(new Hex(-2,0)));Assert.That(g.View(0).Events.Count(e=>e.Kind=="UnitDisplacementPrevented"),Is.EqualTo(1));Assert.That(g.View(0).Events.Any(e=>e.Kind=="UnitPushed"),Is.False);}
  [Test] public void ShiningBladeCancelsProtectionAfterAnActualAttack()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Protect(g);FinishTurn(g);SelectNext(g,"wasp-00-闪耀之刃");if(g.View(0).Phase==Phase.InitiativeChoice)Apply(g,g.View(0).Pending!.ChooserSeat,CommandKind.ChooseInitiative,target:1);while(g.View(0).ActiveSeat!=1)Apply(g,g.View(0).ActiveSeat!.Value,CommandKind.Pass);Apply(g,1,CommandKind.BeginPrimary);Apply(g,1,CommandKind.ChooseAttackTarget,"hero:0");Apply(g,0,CommandKind.Defend,"brogan-13-冲拳");Assert.That(g.View(0).Effects.Any(e=>e.SourceCardId==Card),Is.False);Assert.That(g.View(0).Events.Any(e=>e.Kind=="EffectCancelled" && e.CardId==Card && e.Detail.StartsWith("wasp-00-闪耀之刃")),Is.True);ChargeTests.Restore(cat,g);}
  [Test] public void EffectSurvivesTurnBoundariesAndExpiresAtRoundBoundary()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Protect(g);FinishTurn(g);Assert.That(g.View(0).Effects.Any(e=>e.SourceCardId==Card),Is.True);for(int turn=2;turn<=4;turn++){for(int i=0;i<4;i++)Apply(g,i,CommandKind.SelectCard,g.View(i).OwnCards.First(c=>c.Zone==CardZone.InHand).CardId);FinishTurn(g);}Assert.That(g.View(0).Phase,Is.EqualTo(Phase.RoundEnd));Assert.That(g.View(0).Effects.Any(e=>e.SourceCardId==Card),Is.False);ChargeTests.Restore(cat,g);}
  [Test] public void SourceDefeatCancelsProtection(){var cat=BattlefieldTests.Catalog();var g=Setup(cat);Protect(g);Apply(g,0,CommandKind.DebugDefeatHero,"hero:0",target:1);Assert.That(g.View(0).Effects.Any(e=>e.SourceCardId==Card),Is.False);}
  [Test] public void SelfRecoveredCardCanBeSelectedAgainNextTurn(){var cat=BattlefieldTests.Catalog();var g=Setup(cat);Apply(g,0,CommandKind.BeginPrimary);Apply(g,0,Choice,"recover");FinishTurn(g);Apply(g,0,CommandKind.SelectCard,Card);Assert.That(g.View(0).OwnCards.Single(c=>c.CardId==Card).Zone,Is.EqualTo(CardZone.Selected));ChargeTests.Restore(cat,g);}
  [Test] public void FlashingBladeCannotMoveProtectedOtherEnemyButMayMoveItsAlly()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Protect(g);FinishTurn(g);Apply(g,0,CommandKind.DebugTeleport,"hero:3",cell:new Hex(-2,1));string[] cards={"brogan-00-猛攻","wasp-14-动力助推","sabina-00-近身射击","arien-00-华丽刀锋"};for(int i=0;i<4;i++)Apply(g,i,CommandKind.SelectCard,cards[i]);while(g.View(0).ActiveSeat!=3)Apply(g,g.View(0).ActiveSeat!.Value,CommandKind.Pass);Apply(g,3,CommandKind.BeginPrimary);Apply(g,3,CommandKind.ChooseAttackTarget,"hero:0");Assert.That(g.View(3).EffectTargets,Does.Not.Contain("hero:2"));Assert.That(g.View(3).EffectTargets,Does.Contain("hero:1"));Apply(g,3,CommandKind.ChooseEffectTarget,"hero:1");Apply(g,3,CommandKind.ChooseEffectMove,"skip");Apply(g,0,CommandKind.Defend,"brogan-13-冲拳");ChargeTests.Restore(cat,g);}
  [Test] public void ProtectedMinionStillReturnsAfterFriendlySwap()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat,true);Apply(g,0,CommandKind.DebugTeleport,"hero:0",cell:new Hex(-2,-4));Apply(g,0,CommandKind.DebugTeleport,"hero:2",cell:new Hex(-1,-4));Apply(g,0,CommandKind.DebugTeleport,"minion:-1,-3",cell:new Hex(8,-9));Apply(g,0,CommandKind.DebugTeleport,"minion:-3,1",cell:new Hex(-1,-3));Protect(g);Apply(g,2,CommandKind.BeginPrimary);Apply(g,2,CommandKind.ChooseEffectTarget,"minion:-3,1");Assert.That(g.View(0).Pending!.Kind,Is.EqualTo("minion_return"));g=ChargeTests.Restore(cat,g);Apply(g,0,CommandKind.ChooseMinionReturn,"minion:-3,1",cell:new Hex(-2,-3));Assert.That(g.View(0).Effects.Any(e=>e.SourceCardId==Card),Is.True);ChargeTests.Restore(cat,g);}
  [Test] public void Old49PushQueueKeepsBytesAndContinuesWithoutNewDefaultFields()
  {var cat=BattlefieldTests.Catalog();var save=System.IO.File.ReadAllText(System.IO.Path.Combine(ContentTests.Root(),"tests/fixtures/engine49-burst-push.json"));var g=LocalGameFactory.Restore(cat,save);Assert.That(g.ExportSave(),Is.EqualTo(save));Assert.That(g.View(0).SupportedPrimaryCards,Does.Not.Contain(Card));Apply(g,0,CommandKind.ChooseEffectTarget,"hero:3");Apply(g,0,CommandKind.ChooseEffectTarget,PowerBoostTests.Minion);Apply(g,0,CommandKind.ChooseEffectTarget,"hero:3");Apply(g,3,CommandKind.ForcedDiscard,"arien-13-挑战者");ChargeTests.Restore(cat,g);}
  [Test] public void BardRetrievesResolvedSourceAndCancelsProtection()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Protect(g);FinishTurn(g);Apply(g,0,CommandKind.DebugEquipCard,"brogan-10-吟游诗人",target:0);string[] cards={"brogan-10-吟游诗人","wasp-14-动力助推","sabina-00-近身射击","arien-13-挑战者"};for(int i=0;i<4;i++)Apply(g,i,CommandKind.SelectCard,cards[i]);while(g.View(0).ActiveSeat!=0)Apply(g,g.View(0).ActiveSeat!.Value,CommandKind.Pass);Apply(g,0,CommandKind.BeginPrimary);Apply(g,0,CommandKind.ChooseEffectTarget,"hero:0");Apply(g,0,CommandKind.ChooseRecoveredCard,Card);Assert.That(g.View(0).Effects.Any(e=>e.SourceCardId==Card),Is.False);Assert.That(g.View(0).OwnCards.Single(c=>c.CardId==Card).Zone,Is.EqualTo(CardZone.InHand));ChargeTests.Restore(cat,g);}
 }
}
