using System.Linq;
using Goa2.Application;
using Goa2.Domain;
using Goa2.Infrastructure;
using Goa2.Rules;
using NUnit.Framework;
using static Goa2.Tests.SessionTests;
using static Goa2.Tests.TurnFlowTests;
namespace Goa2.Tests
{
 public sealed class OpportuneMomentTests
 {
  internal const string Card="tigerclaw-07-伺机待发";
  internal static readonly Hex Landing=new Hex(-1,1);
  internal static GameSession Setup(ContentCatalog cat,bool bardTeam=false,string waspCard="wasp-06-静电封锁",bool suppressed=false)
  {
   var g=LocalGameFactory.Create(cat,"opportune-moment",new[]{"A","B","C","D"},42,true);Apply(g,0,CommandKind.DebugPrepare,bardTeam?"tigerclaw,wasp,brogan,arien":"tigerclaw,wasp,arien,brogan");Apply(g,0,CommandKind.DebugEquipCard,"arien-11-潮汐之力",target:bardTeam?3:2);
   Apply(g,0,CommandKind.DebugTeleport,"hero:0",cell:new Hex(-2,0));Apply(g,0,CommandKind.DebugTeleport,"hero:1",cell:suppressed?new Hex(-1,0):new Hex(6,-9));Apply(g,0,CommandKind.DebugTeleport,"hero:2",cell:new Hex(5,-8));Apply(g,0,CommandKind.DebugTeleport,"hero:3",cell:new Hex(7,-9));Apply(g,0,CommandKind.DebugTeleport,"minion:-1,1",cell:new Hex(8,-9));
   string[] cards={Card,waspCard,bardTeam?"brogan-06-铜墙铁壁":"arien-11-潮汐之力",bardTeam?"arien-11-潮汐之力":"brogan-06-铜墙铁壁"};for(int i=0;i<4;i++)Apply(g,i,CommandKind.SelectCard,cards[i]);if(suppressed){Apply(g,1,CommandKind.BeginPrimary);Apply(g,1,CommandKind.ChooseAttackTarget,"hero:0");Apply(g,0,CommandKind.Defend,"tigerclaw-02-偷袭");}else Apply(g,1,CommandKind.Pass);Apply(g,bardTeam?2:3,CommandKind.Pass);if(g.View(0).Phase==Phase.InitiativeChoice)Apply(g,0,CommandKind.ChooseInitiative,target:0);Assert.That(g.View(0).ActiveSeat,Is.EqualTo(0));return g;
  }
  internal static void Place(GameSession g){Apply(g,0,CommandKind.BeginPrimary);Apply(g,0,CommandKind.ChoosePlacement,cell:Landing);}
  internal static void Activate(GameSession g){Place(g);Apply(g,g.View(0).ActiveSeat!.Value,CommandKind.Pass);}
  private static GameState State(GameSession g)=>new JsonStateCodec().Read(g.ExportSave());
  [Test] public void ContractAndEngineGate(){var c=BattlefieldTests.Catalog().Card(Card);Assert.That(c.Initiative,Is.EqualTo(3));Assert.That(c.SubtypeValue,Is.EqualTo(2));Assert.That(c.PrimaryCategory,Is.EqualTo("基础技能"));Assert.That(CombatRules.HasPrimaryProgram(c),Is.True);Assert.That(CombatRules.HasPrimaryProgram(c,50),Is.False);c.Text+="可选";Assert.That(CombatRules.HasPrimaryProgram(c),Is.False);}
  [Test] public void PlacementMayUseSpawnAndOnlyGrantsImmunityNextTurn()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Apply(g,0,CommandKind.BeginPrimary);Assert.That(g.View(0).Placements,Does.Contain(Landing));g=ChargeTests.Restore(cat,g);Apply(g,0,CommandKind.ChoosePlacement,cell:Landing);var s=State(g);Assert.That(s.Units.Single(u=>u.Seat==0).Position,Is.EqualTo(Landing));Assert.That(EffectRules.CanBeAttacked(s,s.Units.Single(u=>u.Seat==1),s.Units.Single(u=>u.Seat==0),false),Is.True);Assert.That(g.View(0).Effects.Single(e=>e.SourceCardId==Card).Window.StartTurn,Is.EqualTo(2));Apply(g,2,CommandKind.Pass);g=ChargeTests.Restore(cat,g);s=State(g);Assert.That(EffectRules.CanBeAttacked(s,s.Units.Single(u=>u.Seat==1),s.Units.Single(u=>u.Seat==0),false),Is.False);Assert.That(g.View(0).Events.Any(e=>e.Kind=="UnitMoved"),Is.False);}
  [Test] public void InvalidPlacementAndNonOwnerAreAtomicAndDuplicateDoesNotRepeat()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Apply(g,0,CommandKind.BeginPrimary);foreach(var cell in new[]{new Hex(-2,0),new Hex(-3,0),new Hex(-2,-1),new Hex(6,-8)}){var save=g.ExportSave();Assert.That(g.Execute(0,Cmd(g,0,CommandKind.ChoosePlacement,destination:cell)).Accepted,Is.False);Assert.That(g.ExportSave(),Is.EqualTo(save));}var before=g.ExportSave();Assert.That(g.Execute(1,Cmd(g,1,CommandKind.ChoosePlacement,destination:Landing)).Accepted,Is.False);Assert.That(g.ExportSave(),Is.EqualTo(before));var cmd=Cmd(g,0,CommandKind.ChoosePlacement,destination:Landing);Assert.That(g.Execute(0,cmd).Accepted,Is.True);var after=g.ExportSave();Assert.That(g.Execute(0,cmd).Duplicate,Is.True);Assert.That(g.ExportSave(),Is.EqualTo(after));}
  [Test] public void NoAdjacentObstacleDoesNotPlaceOrCreateEffect()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);var s=State(g);var cell=cat.Cells.First(c=>!c.Obstacle && s.Units.All(u=>u.Seat==0 || u.Position!=c.Position && u.Position.Distance(c.Position)!=1) && c.Position.Neighbors().All(p=>cat.Cell(p)?.Obstacle!=true));Apply(g,0,CommandKind.DebugTeleport,"hero:0",cell:cell.Position);Apply(g,0,CommandKind.BeginPrimary);Assert.That(g.View(0).Effects,Is.Empty);Assert.That(g.View(0).Events.Any(e=>e.Kind=="UnitPlaced"),Is.False);}
  [Test] public void RangeUsesSkillBonusRatherThanRangedBonus()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Apply(g,0,CommandKind.BeginPrimary);var s=State(g);var source=s.Units.Single(u=>u.Seat==0);var cell=cat.Cells.First(c=>!c.Obstacle && c.Position.Distance(source.Position)==3 && s.Units.All(u=>u.Position!=c.Position && (u.Team==source.Team || u.Position.Distance(c.Position)!=1)));s.Players[0].RangedBonus=9;Assert.That(GameRules.LegalPlacements(cat,s,0),Has.No.Member(cell.Position));s.Players[0].RangeBonus=1;Assert.That(GameRules.LegalPlacements(cat,s,0),Does.Contain(cell.Position));}
  [Test] public void OtherFriendlyAndEnemyActionsCannotDisplaceButOwnActionsCan()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Activate(g);var s=State(g);var tiger=s.Units.Single(u=>u.Seat==0);Assert.That(EffectRules.CanDisplace(cat,s,1,tiger),Is.False);Assert.That(EffectRules.CanDisplace(cat,s,2,tiger),Is.False);Assert.That(EffectRules.CanDisplace(cat,s,0,tiger),Is.True);Assert.That(GameRules.LegalDebugAttacks(s,1),Does.Not.Contain(tiger.Id));}
  [Test] public void FourthTurnStillPlacesButDoesNotScheduleAcrossRound()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);var s=State(g);s.Turn=4;new GameRules().Apply(cat,s,new Command{ActorSeat=0,Kind=CommandKind.BeginPrimary});new GameRules().Apply(cat,s,new Command{ActorSeat=0,Kind=CommandKind.ChoosePlacement,Destination=Landing});Assert.That(s.Units.Single(u=>u.Seat==0).Position,Is.EqualTo(Landing));Assert.That(s.Effects,Is.Empty);Assert.That(s.Events.Any(e=>e.Kind=="EffectNotScheduled"),Is.True);}
  [Test] public void ScheduledSourceDefeatRemovesFutureImmunity()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Place(g);Apply(g,0,CommandKind.DebugDefeatHero,"hero:0",target:1);Assert.That(g.View(0).Effects,Is.Empty);ChargeTests.Restore(cat,g);}
  // Isolated deferred-response primitive: current Tigerclaw has no ranged attack to trigger this Wasp response naturally.
  [Test] public void ImmuneDeferredDiscardEmitsOnlyOneSkipAndDoesNotFallThroughToEmptyHand()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Activate(g);var s=State(g);s.Execution=new CardExecution{ControllerSeat=0,CardId="tigerclaw-03-背刺",DefenseResponse=new DefenseResponse{SourceCardId="wasp-08-偏转屏障",SourceUnitId="hero:1",ControllerSeat=1,AttackerSeat=0,AttackerUnitId="hero:0",ProgramId="block_ranged_discard_attacker",ProgramVersion=1}};var method=typeof(GameRules).GetMethod("ContinueDefenseResponse",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static)!;Assert.That(method.Invoke(null,new object[]{cat,s,new Command{ActorSeat=1}}),Is.True);Assert.That(s.Events.Count(e=>e.Kind=="ForcedDiscardSkipped"),Is.EqualTo(1));Assert.That(s.Events.Last(e=>e.Kind=="ForcedDiscardSkipped").Detail,Is.EqualTo("immune"));Assert.That(s.Units.Any(u=>u.Seat==0),Is.True);}
  internal static void NextCards(GameSession g,string tiger="tigerclaw-02-偷袭",string wasp="wasp-00-闪耀之刃",string arien="arien-00-华丽刀锋",string brogan="brogan-13-冲拳")
  {string[] cards={tiger,wasp,arien,brogan};for(int i=0;i<4;i++)Apply(g,i,CommandKind.SelectCard,cards[i]);}
  internal static void AdvanceTo(GameSession g,int seat)
  {int steps=0;while(g.View(0).Phase!=Phase.Action || g.View(0).ActiveSeat!=seat){Assert.That(++steps,Is.LessThan(12));var v=g.View(0);if(v.Phase==Phase.InitiativeChoice)Apply(g,v.Pending!.ChooserSeat,CommandKind.ChooseInitiative,target:v.Pending.CandidateSeats.Contains(seat)?seat:v.Pending.CandidateSeats.First());else{Assert.That(v.Phase,Is.EqualTo(Phase.Action));Apply(g,v.ActiveSeat!.Value,CommandKind.Pass);}}}
  [TestCase(1)] [TestCase(2)] public void MovementTraversesEnemyOrFriendlyUnitButCannotStopOnUnitOrTerrain(int middleSeat)
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Activate(g);Apply(g,0,CommandKind.DebugTeleport,"hero:"+middleSeat,cell:new Hex(-1,0));NextCards(g);AdvanceTo(g,0);var move=g.View(0).SecondaryMoves.Single(m=>m.Destination==new Hex(-1,-1));Assert.That(move.Path,Is.EqualTo(new[]{Landing,new Hex(-1,0),new Hex(-1,-1)}));foreach(var invalid in new[]{new Hex(-1,0),new Hex(0,0)}){var before=g.ExportSave();Assert.That(g.Execute(0,Cmd(g,0,CommandKind.Move,destination:invalid)).Accepted,Is.False);Assert.That(g.ExportSave(),Is.EqualTo(before));}Assert.That(g.View(0).SecondaryMoves.All(m=>m.Path.All(p=>cat.Cell(p)?.Obstacle==false)),Is.True);Apply(g,0,CommandKind.Move,cell:move.Destination);ChargeTests.Restore(cat,g);}
  [Test] public void StraightCardTextMovementAlsoTraversesUnits()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Activate(g);Apply(g,0,CommandKind.DebugTeleport,"hero:1",cell:new Hex(-1,0));NextCards(g,tiger:"tigerclaw-08-偷天妙手");AdvanceTo(g,0);Apply(g,0,CommandKind.BeginPrimary);Apply(g,0,CommandKind.ChooseEffectMove,"skip");Assert.That(g.View(0).EffectMoves.Any(m=>m.Destination==new Hex(-1,-1) && m.Path.Contains(new Hex(-1,0))),Is.True);Apply(g,0,CommandKind.ChooseEffectMove,cell:new Hex(-1,-1));ChargeTests.Restore(cat,g);}
  [Test] public void ShiningBladeCannotTargetOrCancelImmuneTigerAndItsSuppressionDoesNotRestrictOwnSkill()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Activate(g);Apply(g,0,CommandKind.DebugTeleport,"hero:1",cell:new Hex(-1,0));Apply(g,0,CommandKind.DebugTeleport,"hero:2",cell:new Hex(-2,0));NextCards(g,tiger:"tigerclaw-08-偷天妙手");Apply(g,1,CommandKind.BeginPrimary);Assert.That(g.View(1).AttackTargets,Does.Not.Contain("hero:0"));Assert.That(g.View(1).AttackTargets,Does.Contain("hero:2"));Apply(g,1,CommandKind.ChooseAttackTarget,"hero:2");Apply(g,2,CommandKind.Defend,"arien-13-挑战者");Assert.That(g.View(0).Effects.Any(e=>e.SourceCardId==Card),Is.True);AdvanceTo(g,0);Assert.That(g.View(0).PrimaryRestriction,Is.Empty);Apply(g,0,CommandKind.BeginPrimary);Assert.That(g.View(0).Pending!.Kind,Is.EqualTo("effect_move"));ChargeTests.Restore(cat,g);}
  [Test] public void EnemyGroupPushCannotSelectImmuneHero()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Activate(g);Apply(g,0,CommandKind.DebugTeleport,"hero:1",cell:new Hex(-1,0));Apply(g,0,CommandKind.DebugEquipCard,"wasp-14-动力助推",target:1);NextCards(g,wasp:"wasp-14-动力助推");AdvanceTo(g,1);Apply(g,1,CommandKind.BeginPrimary);Assert.That(g.View(1).EffectTargets,Does.Not.Contain("hero:0"));Assert.That(g.View(0).Events.Any(e=>e.Kind=="UnitPushed" && e.Seat==0),Is.False);ChargeTests.Restore(cat,g);}
  [Test] public void FriendlySwapCannotSelectImmuneTiger()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Activate(g);Apply(g,0,CommandKind.DebugTeleport,"hero:2",cell:new Hex(-2,0));Apply(g,0,CommandKind.DebugEquipCard,"arien-08-奥术换位",target:2);NextCards(g,arien:"arien-08-奥术换位");AdvanceTo(g,2);Apply(g,2,CommandKind.BeginPrimary);Assert.That(g.View(2).EffectTargets,Does.Not.Contain("hero:0"));Assert.That(g.View(2).EffectTargets,Does.Contain("minion:-3,1"));ChargeTests.Restore(cat,g);}
  [Test] public void ImmunityExpiresAfterNextTurn()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Activate(g);NextCards(g);IronWallTests.FinishTurn(g);Assert.That(g.View(0).Turn,Is.EqualTo(3));Assert.That(g.View(0).Effects.Any(e=>e.SourceCardId==Card),Is.False);ChargeTests.Restore(cat,g);}
  [Test] public void Old50OptionWindowStillReturnsSourceWithoutAddingEffects()
  {var cat=BattlefieldTests.Catalog();var save=System.IO.File.ReadAllText(System.IO.Path.Combine(ContentTests.Root(),"tests/fixtures/engine50-wall-choice.json"));var g=LocalGameFactory.Restore(cat,save);Assert.That(g.ExportSave(),Is.EqualTo(save));Assert.That(g.View(0).SupportedPrimaryCards,Does.Not.Contain(Card));Apply(g,0,CommandKind.ChoosePrimaryOption,"recover");ChargeTests.Restore(cat,g);Assert.That(g.View(0).OwnCards.Single(c=>c.CardId==IronWallTests.Card).Zone,Is.EqualTo(CardZone.InHand));}
  [Test] public void ShockExtraDiscardCannotSelectImmuneTiger()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Activate(g);Apply(g,0,CommandKind.DebugTeleport,"hero:1",cell:new Hex(-1,0));Apply(g,0,CommandKind.DebugTeleport,"hero:2",cell:new Hex(-2,0));NextCards(g,wasp:"wasp-01-电击");AdvanceTo(g,1);Apply(g,1,CommandKind.BeginPrimary);Apply(g,1,CommandKind.ChooseAttackTarget,"hero:2");Assert.That(g.View(2).Pending!.Kind,Is.EqualTo("defense"));Assert.That(g.View(0).Events.Any(e=>e.Kind=="ForcedDiscardRequired"),Is.False);Apply(g,2,CommandKind.Defend,"arien-13-挑战者");ChargeTests.Restore(cat,g);}
  [Test] public void FriendlyBardCannotRecoverForImmuneTigerEvenWhenAdjacentEnemyConditionHolds()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat,bardTeam:true);Activate(g);Apply(g,0,CommandKind.DebugTeleport,"hero:1",cell:new Hex(-1,0));Apply(g,0,CommandKind.DebugTeleport,"hero:2",cell:new Hex(-2,1));Apply(g,0,CommandKind.DebugEquipCard,"brogan-10-吟游诗人",target:2);Apply(g,0,CommandKind.DebugDiscard,"tigerclaw-18-躲闪",target:0);string[] cards={"tigerclaw-02-偷袭","wasp-00-闪耀之刃","brogan-10-吟游诗人","arien-00-华丽刀锋"};for(int i=0;i<4;i++)Apply(g,i,CommandKind.SelectCard,cards[i]);AdvanceTo(g,2);Apply(g,2,CommandKind.BeginPrimary);Assert.That(g.View(2).EffectTargets,Does.Not.Contain("hero:0"));Assert.That(g.View(2).EffectTargets,Does.Contain("hero:2"));var s=State(g);s.Effects.RemoveAll(e=>e.SourceCardId==Card);Assert.That(GameRules.LegalEffectTargets(cat,s,2),Does.Contain("hero:0"));ChargeTests.Restore(cat,g);}
  [Test] public void ImmuneMovementCanCrossActualStaticBoundaryAndOccupiedIntermediateCell()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat,waspCard:"wasp-13-控物");Activate(g);Apply(g,0,CommandKind.DebugTeleport,"hero:1",cell:new Hex(-1,0));NextCards(g,wasp:"wasp-06-静电封锁");AdvanceTo(g,1);Apply(g,1,CommandKind.BeginPrimary);AdvanceTo(g,0);var landing=new Hex(-1,3);Assert.That(g.View(0).SecondaryMoves.Single(m=>m.Destination==landing).Path,Does.Contain(new Hex(-1,2)));var s=State(g);s.Effects.RemoveAll(e=>e.SourceCardId==Card);Assert.That(MovementRules.LegalMoves(cat,s,0,MoveMode.Secondary).Any(m=>m.Destination==landing),Is.False);Apply(g,0,CommandKind.Move,cell:landing);ChargeTests.Restore(cat,g);}
  [Test] public void AdjacentTerrainAloneSatisfiesCondition()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Apply(g,0,CommandKind.DebugTeleport,"hero:0",cell:new Hex(-1,0));Assert.That(State(g).Units.Any(u=>u.Seat!=0 && u.Position.Distance(new Hex(-1,0))==1),Is.False);Apply(g,0,CommandKind.BeginPrimary);Apply(g,0,CommandKind.ChoosePlacement,cell:new Hex(-1,-1));Assert.That(g.View(0).Effects.Any(e=>e.SourceCardId==Card),Is.True);}
  [Test] public void NoSafeDestinationEndsWithoutFutureEffect()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat);Apply(g,0,CommandKind.DebugTeleport,"hero:1",cell:new Hex(-1,0));Apply(g,0,CommandKind.DebugTeleport,"hero:3",cell:new Hex(-1,-2));Apply(g,0,CommandKind.DebugTeleport,"minion:1,-1",cell:new Hex(-2,2));Apply(g,0,CommandKind.BeginPrimary);Assert.That(g.View(0).Effects.Any(e=>e.SourceCardId==Card),Is.False);Assert.That(g.View(0).Events.Any(e=>e.Kind=="UnitPlaced"),Is.False);ChargeTests.Restore(cat,g);}
  [Test] public void FutureImmunityCannotBypassCurrentSkillSuppression()
  {var cat=BattlefieldTests.Catalog();var g=Setup(cat,waspCard:"wasp-00-闪耀之刃",suppressed:true);Assert.That(g.View(0).PrimaryRestriction,Is.EqualTo("wasp-00-闪耀之刃"));var before=g.ExportSave();Assert.That(g.Execute(0,Cmd(g,0,CommandKind.BeginPrimary)).Code,Is.EqualTo("primary_restricted"));Assert.That(g.ExportSave(),Is.EqualTo(before));}
 }
}
